/**
 * Shared Studio Next helpers for deploy, seed, and smoke scripts.
 * Network: GenLayer Studio Next (CLI `studio-dev`, genlayer-js `studioDevnet`, chain 61997).
 */
import { existsSync, readFileSync, writeFileSync, appendFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadEnv } from "dotenv";
import { createAccount, createClient, generatePrivateKey, isSuccessful } from "genlayer-js";
import { studioDevnet } from "genlayer-js/chains";
import type { GenLayerTransaction } from "genlayer-js/types";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const ENV_FILE = resolve(ROOT, ".env");
export const DEPLOYMENT_FILE = resolve(ROOT, "deployments", "studio-next.json");
export const PROOF_FILE = resolve(ROOT, "deployments", "demo-proof.json");
export const FRONTEND_DEPLOYMENT_FILE = resolve(ROOT, "frontend", "lib", "deployment.generated.json");
// v2 artifacts are intentionally separate. Never point v2 helpers at v1 files:
// the v1 address and finalized proof records are part of the release evidence.
export const V2_DEPLOYMENT_FILE = resolve(ROOT, "deployments", "studio-next-v2.json");
export const V2_PROOF_FILE = resolve(ROOT, "deployments", "demo-proof-v2.json");
export const V2_FRONTEND_DEPLOYMENT_FILE = resolve(ROOT, "frontend", "lib", "deployment.v2.generated.json");
export const V2_FRONTEND_PROOF_FILE = resolve(ROOT, "frontend", "lib", "proof.v2.generated.json");

loadEnv({ path: ENV_FILE, quiet: true });

export const RPC_URL = "https://studio-dev.genlayer.com/api";
export const CHAIN_ID = 61997;
export const EXPLORER_URL = process.env.EXPLORER_URL ?? "https://explorer-studio-dev.genlayer.com";
export const FIXTURE_BASE_URL = (process.env.FIXTURE_BASE_URL ?? "https://redemption-guard.vercel.app").replace(/\/$/, "");

if (studioDevnet.id !== CHAIN_ID) {
  throw new Error(`studioDevnet chain id ${studioDevnet.id} != ${CHAIN_ID}; check genlayer-js version`);
}

export type Hex = `0x${string}`;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Studio Next rate-limits each client to 30 RPC requests per minute. A
 * rate-limited request is rejected before processing, so retrying is safe.
 */
export async function withRetry<T>(label: string, fn: () => Promise<T>, attempts = 8): Promise<T> {
  for (let i = 1; ; i++) {
    try {
      return await fn();
    } catch (err) {
      const text = err instanceof Error ? `${err.message} ${String((err as { details?: string }).details ?? "")}` : String(err);
      if (i >= attempts || !/rate limit|429|too many requests/i.test(text)) throw err;
      const wait = 15_000 * i;
      console.log(`  (rate limited during ${label}; retrying in ${wait / 1000}s)`);
      await sleep(wait);
    }
  }
}

export function explorerTx(hash: string): string {
  return `${EXPLORER_URL}/tx/${hash}`;
}

export function explorerAddress(address: string): string {
  return `${EXPLORER_URL}/address/${address}`;
}

/** Load the deployer key from .env, creating a fresh local-only key if absent. Never printed. */
export function loadOrCreateKey(): Hex {
  const existing = process.env.DEPLOYER_PRIVATE_KEY?.trim();
  if (existing && /^0x[0-9a-fA-F]{64}$/.test(existing)) return existing as Hex;
  const key = generatePrivateKey();
  const line = `${existsSync(ENV_FILE) ? "\n" : ""}# Generated by scripts/lib.ts for Studio Next only. Never commit.\nDEPLOYER_PRIVATE_KEY=${key}\n`;
  appendFileSync(ENV_FILE, line, { encoding: "utf8" });
  process.env.DEPLOYER_PRIVATE_KEY = key;
  console.log(`Created a new Studio Next deployer key in ${ENV_FILE} (gitignored).`);
  return key;
}

export function makeClients() {
  const account = createAccount(loadOrCreateKey());
  const client = createClient({ chain: studioDevnet, endpoint: RPC_URL, account });
  const reader = createClient({ chain: studioDevnet, endpoint: RPC_URL });
  return { account, client, reader };
}

async function rpc<T>(method: string, params: unknown[]): Promise<T> {
  return withRetry(method, () => rpcOnce<T>(method, params));
}

async function rpcOnce<T>(method: string, params: unknown[]): Promise<T> {
  const res = await fetch(RPC_URL, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: Date.now(), method, params }),
  });
  const body = (await res.json()) as { result?: T; error?: { message: string } };
  if (res.status === 429) throw new Error(`${method}: rate limit (HTTP 429)`);
  if (body.error) throw new Error(`${method}: ${body.error.message}`);
  return body.result as T;
}

export async function checkNetwork(): Promise<void> {
  const chainId = parseInt(await rpc<string>("eth_chainId", []), 16);
  if (chainId !== CHAIN_ID) throw new Error(`RPC ${RPC_URL} reports chain ${chainId}, expected ${CHAIN_ID}`);
}

/** Studio Next exposes the documented `sim_fundAccount` faucet RPC. */
export async function ensureFunded(address: string, minimumWei = 10n ** 19n): Promise<bigint> {
  const balance = BigInt(await rpc<string>("eth_getBalance", [address, "latest"]));
  if (balance >= minimumWei) return balance;
  // 100 GEN; JSON.stringify keeps integers below 1e21 in plain digits.
  await rpc("sim_fundAccount", [address, 100 * 1e18]);
  const after = BigInt(await rpc<string>("eth_getBalance", [address, "latest"]));
  if (after < minimumWei) throw new Error(`Funding ${address} failed; balance ${after}`);
  return after;
}

export type TxOutcome = {
  hash: Hex;
  statusName: string;
  executionResultName: string;
  successful: boolean;
  resultName?: string;
  errorText?: string;
  validators?: number;
  votes?: Record<string, string>;
  explorer: string;
};

export async function waitOutcome(
  client: ReturnType<typeof makeClients>["client"],
  hash: Hex,
  label: string,
): Promise<TxOutcome> {
  process.stdout.write(`  ${label}: ${hash} … `);
  const tx = (await withRetry("waitForTransactionReceipt", () =>
    client.waitForTransactionReceipt({
      hash: hash as never,
      waitUntil: "decided",
      interval: 8000,
      retries: 120,
      fullTransaction: true,
    }),
  )) as GenLayerTransaction;
  const outcome: TxOutcome = {
    hash,
    statusName: String(tx.statusName ?? tx.status ?? "UNKNOWN"),
    executionResultName: String(tx.txExecutionResultName ?? "UNKNOWN"),
    successful: isSuccessful(tx),
    resultName: tx.resultName ? String(tx.resultName) : undefined,
    explorer: explorerTx(hash),
  };
  try {
    const details = await readConsensusDetails(hash);
    outcome.validators = details.validators;
    outcome.votes = details.votes;
    if (!outcome.successful) outcome.errorText = details.errorText;
  } catch {
    // details are informational; the outcome above is authoritative
  }
  console.log(`${outcome.statusName} / ${outcome.executionResultName}${outcome.errorText ? ` — ${outcome.errorText}` : ""}`);
  return outcome;
}

type RawTx = {
  status?: string;
  txExecutionResultName?: string;
  num_of_initial_validators?: number;
  consensus_data?: { votes?: Record<string, string>; leader_receipt?: { result?: string }[] };
};

/**
 * Studio Next does not serve gen_dbg_traceTransaction, so read the raw
 * transaction: leader_receipt[0].result is base64 of a 1-byte result code
 * (0 = return, 1 = UserError, 2 = VMError) followed by the payload.
 */
export async function readConsensusDetails(hash: Hex): Promise<{
  statusName?: string;
  executionResultName?: string;
  validators?: number;
  votes?: Record<string, string>;
  resultCode?: number;
  errorText?: string;
}> {
  const tx = await rpc<RawTx>("eth_getTransactionByHash", [hash]);
  const raw = tx?.consensus_data?.leader_receipt?.[0]?.result;
  let resultCode: number | undefined;
  let errorText: string | undefined;
  if (typeof raw === "string" && raw.length > 0) {
    const bytes = Buffer.from(raw, "base64");
    resultCode = bytes[0];
    if (resultCode !== 0) errorText = bytes.subarray(1).toString("utf8").slice(0, 300);
  }
  return {
    statusName: tx?.status,
    executionResultName: tx?.txExecutionResultName,
    validators: tx?.num_of_initial_validators,
    votes: tx?.consensus_data?.votes,
    resultCode,
    errorText,
  };
}

export function readJson<T>(file: string): T | undefined {
  if (!existsSync(file)) return undefined;
  return JSON.parse(readFileSync(file, "utf8")) as T;
}

export function writeJson(file: string, data: unknown): void {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(data, (_k, v) => (typeof v === "bigint" ? v.toString() : v), 2)}\n`);
}

export type Deployment = {
  network: "studio-next";
  chainId: number;
  rpcUrl: string;
  explorerUrl: string;
  contractAddress: Hex;
  deployTx: TxOutcome;
  deployer: string;
  deployedAt: string;
  runner: string;
  fixtureBaseUrl: string;
  assets: { assetId: string; name: string; issuer: string; domains: string[]; tx: TxOutcome }[];
};

export const DEMO_ASSETS = () => {
  const host = new URL(FIXTURE_BASE_URL).host;
  return [
    { assetId: "NWUSD", name: "Northwind Dollar", issuer: "Northwind Reserve Trust (fictional)", domains: [host] },
    { assetId: "HLUSD", name: "Halcyon Dollar", issuer: "Halcyon Settlement Co. (fictional)", domains: [host] },
  ];
};

export const FIXTURES = () => ({
  operational: `${FIXTURE_BASE_URL}/evidence/northwind-redemptions-operational.html`,
  suspended: `${FIXTURE_BASE_URL}/evidence/halcyon-redemptions-suspended.html`,
  unclear: `${FIXTURE_BASE_URL}/evidence/halcyon-status-unclear.html`,
});

export async function assertFixturesPublic(): Promise<void> {
  for (const url of Object.values(FIXTURES())) {
    const res = await fetch(url, { redirect: "manual" });
    if (res.status !== 200) throw new Error(`Fixture not publicly reachable (${res.status}): ${url}`);
  }
}

type Client = ReturnType<typeof makeClients>["client"];

/**
 * Studio Next rejects zero-fee transactions. Prefer a simulation-backed
 * estimate for writes (measures real execution), falling back to the network
 * default policy when the simulation itself reverts (e.g. a blocked request).
 */
export async function feesFor(
  client: Client,
  call?: { address: Hex; functionName: string; args: (string | number | bigint)[] },
): Promise<{ distribution: unknown; feeValue: bigint }> {
  if (call) {
    try {
      const est = await withRetry("estimateTransactionFeesForWrite", () => client.estimateTransactionFeesForWrite({ ...call }), 4);
      return { distribution: est.distribution, feeValue: est.feeValue };
    } catch (err) {
      console.log(`  (simulation estimate unavailable for ${call.functionName}: ${String(err).slice(0, 120)}; using network default)`);
    }
  }
  const est = await withRetry("estimateTransactionFees", () => client.estimateTransactionFees());
  return { distribution: est.distribution, feeValue: est.feeValue };
}

export async function write(
  client: Client,
  address: Hex,
  functionName: string,
  args: (string | number | bigint)[],
  label: string,
  opts: { simulateFees?: boolean } = {},
): Promise<TxOutcome> {
  const fees = await feesFor(client, opts.simulateFees === false ? undefined : { address, functionName, args });
  const hash = (await withRetry(`write ${functionName}`, () =>
    client.writeContract({ address, functionName, args, fees: fees as never }),
  )) as Hex;
  return waitOutcome(client, hash, label);
}

export const FRONTEND_PROOF_FILE = resolve(ROOT, "frontend", "lib", "proof.generated.json");

/** Compact, public copy of the proof flows for the dashboard's proof panel. */
export function writeFrontendProof(proof: {
  contractAddress: string;
  generatedAt: string;
  flows: { name: string; assetId: string; onChainStatus: string; assessmentId: number; exposureAllowed: boolean; assessTx: TxOutcome; exposureTx: TxOutcome }[];
}): void {
  writeJson(FRONTEND_PROOF_FILE, {
    contractAddress: proof.contractAddress,
    generatedAt: proof.generatedAt,
    flows: proof.flows.map((f) => ({
      name: f.name,
      assetId: f.assetId,
      status: f.onChainStatus,
      assessmentId: f.assessmentId,
      exposureAllowed: f.exposureAllowed,
      assess: { hash: f.assessTx.hash, statusName: f.assessTx.statusName, executionResultName: f.assessTx.executionResultName, validators: f.assessTx.validators, votes: f.assessTx.votes },
      exposure: { hash: f.exposureTx.hash, statusName: f.exposureTx.statusName, executionResultName: f.exposureTx.executionResultName, errorText: f.exposureTx.errorText },
    })),
  });
}
